services:
  backend:
    build:
      context: ./backend
    container_name: backend
    working_dir: /backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_AUTH_URL=https://chatguru.protectdata.app
    volumes:
      - "./frontend:/app/public"
      - "./src:/app/src"
    depends_on:
      - backend
