version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    working_dir: /frontend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    working_dir: /backend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app/public"
      - "./src:/app/src"
    depends_on:
      - backend
